### Numpy

* Numpy stands for numerical python
* It is a python library used to works with arrays
* It also has functions to works with linear alzebra,fourier transforms, matrices etc
* array object here is called ndarray. ndarray is 5x faster than lists in python

In [3]:
### importing the library

import numpy 

In [4]:
import numpy as np

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
### creating an  1-d array

a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
print(type(a))


<class 'numpy.ndarray'>


In [8]:
a.ndim #no of dimensions of an array

1

In [9]:
a.dtype #data type of an array

dtype('int32')

In [10]:
a.shape   # shape as a tuple

(6,)

In [11]:
a.size #no of elements inside an array

6

In [12]:
a.itemsize  #returns each item size in bytes

4

In [13]:
a=np.array([1,2,3,4],np.int8)
a

array([1, 2, 3, 4], dtype=int8)

In [14]:
2**8-1

255

In [15]:
a=np.array([1,2,3,4,512],np.int8)
a

array([1, 2, 3, 4, 0], dtype=int8)

In [17]:
### float 
ar=np.array([10,20,30,69.8])
print(ar)
print(ar.dtype)

[10.  20.  30.  69.8]
float64


In [18]:
### string 

b=np.array([100,78,56,'python'])
print(b)

['100' '78' '56' 'python']


In [20]:
dir(np.dtype)

['__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'alignment',
 'base',
 'byteorder',
 'char',
 'descr',
 'fields',
 'flags',
 'hasobject',
 'isalignedstruct',
 'isbuiltin',
 'isnative',
 'itemsize',
 'kind',
 'metadata',
 'name',
 'names',
 'ndim',
 'newbyteorder',
 'num',
 'shape',
 'str',
 'subdtype',
 'type']

In [23]:
### appending single element to an array

c=np.array([9,8,90])
c=np.append(c,34)  
c

array([ 9,  8, 90, 34])

In [24]:
### appending multiple elements to an array

c=np.append(c,[100,200,300])
c

array([  9,   8,  90,  34, 100, 200, 300])

### creating ndarray using range()

In [29]:
r=np.array(range(1,9,2))  #start,stop,step
print(r)
print(type(r))

[1 3 5 7]
<class 'numpy.ndarray'>


In [30]:
l=[90,89,76,56]   #creating ndarray using list
a=np.array(l)
print(a)
print(type(a))

[90 89 76 56]
<class 'numpy.ndarray'>


### creating ndarray using arange()

In [31]:
a=np.arange(1,11)  #range of values
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [32]:
a=np.arange(1,11,2)  #range of values with step value
print(a)
print(type(a))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [33]:
a.nbytes   #checking memory space occupied by an array

20

In [35]:
print(a.itemsize)  #checking each element size
print(len(a))      # length of an array

4
5


In [36]:
print(np.arange(11,21))
print(np.arange(5))
print(np.arange(4,1))

[11 12 13 14 15 16 17 18 19 20]
[0 1 2 3 4]
[]


In [37]:
### creating array using linspace

a=np.linspace(1,10,20)  #creating array within given range with required no of elelments
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [38]:
a=np.logspace(1,10,20)  #creating an array within given range
#with required no of elements with their log values
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [39]:
np.full(10,"numpy")  #repeating required no of times and making into array

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy',
       'numpy', 'numpy', 'numpy'], dtype='<U5')

In [40]:
np.full(10,'1 2')

array(['1 2', '1 2', '1 2', '1 2', '1 2', '1 2', '1 2', '1 2', '1 2',
       '1 2'], dtype='<U3')

In [42]:
np.ones(10,dtype=int)  #repeating ones for required no of times

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
np.zeros(10,dtype=int)  #repeating zeros with defined no of times

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### creating 2D array

In [46]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,80,78,67]])
print(a)
print(type(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 80 78 67]]
<class 'numpy.ndarray'>


In [47]:
print(a.ndim)
print(a.dtype)
print(a.nbytes)
print(a.itemsize)


2
int32
48
4


In [48]:
### 3D array : combination of more no of 2-d arrays

a=np.array([[[9,8,7],[4,5,6]],[[1,2,3],[30,67,65]]])
a

array([[[ 9,  8,  7],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [30, 67, 65]]])

In [50]:
print(type(a))
print(a.ndim)

<class 'numpy.ndarray'>
3


In [52]:
### Multidimensional array

a=np.array([1,2,3,4,5],ndmin=20)
a

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]]]]]]]]]]]])

In [53]:
a.ndim

20

### Accessing Elements from an araray


In [54]:
### 1-d array

a=np.array([10,202,30,40,50,609])
a

array([ 10, 202,  30,  40,  50, 609])

In [55]:
# forward index  --> starts from 0
# backward indexing --> starts from -1 from backside

In [56]:
a[3]

40

In [58]:
a[-3]

40

In [59]:
a[-5]

202

In [60]:
a

array([ 10, 202,  30,  40,  50, 609])

In [61]:
### 202,30,40

a[1:4]

array([202,  30,  40])

In [62]:
a[::-1]  #reverse order

array([609,  50,  40,  30, 202,  10])

In [63]:
###2-D array element accessing

b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
b.size

8

In [65]:
b.shape

(2, 4)

In [66]:
b[0]  #1-st row

array([1, 2, 3, 4])

In [67]:
b[1]  #2nd row

array([5, 6, 7, 8])

In [68]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
b[1,2]  #accessing a particular element by using row, column index

7

In [70]:
b[0][0]

1

In [71]:
b[:,0]   # 1-st column

array([1, 5])

In [72]:
b[:,-2]

array([3, 7])

In [73]:
b[:,-2:]  #row index slicing,element index slicing

array([[3, 4],
       [7, 8]])

In [74]:
b[:,1:3]

array([[2, 3],
       [6, 7]])

In [75]:
### 3-d array 

a=np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]]])

In [76]:
a[0]   #2-d index

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
a[1]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [78]:
a[0,0]

array([1, 2, 3, 4])

In [79]:
a[0,1]

array([5, 6, 7, 8])

In [80]:
a[1,0]

array([10, 20, 30, 40])

In [81]:
a[1,1]

array([50, 60, 70, 80])

In [82]:
a[1,1,2]

70

In [83]:
a[1,0,2]

30

In [84]:
a[0,0,-2]

3

In [85]:
a[:,0,-1]   #0th column, -1 element

array([ 4, 40])

In [86]:
a[1,0,-1]

40

In [87]:
### shape of an array

a=np.array([4,6,7])
a.shape

(3,)

In [88]:
b=np.array([[1,2,3],[4,5,6]])
b.shape

(2, 3)

In [89]:
c=np.array([[[1,2],[2,4]],[[3,5],[8,9]]])
c.shape

(2, 2, 2)

### Reshaping of the array

In [90]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [91]:
b=a.reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [92]:
b.ndim

2

In [93]:
a.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [94]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [95]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [96]:
a.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [97]:
a.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [98]:
a.reshape(1,19)

ValueError: cannot reshape array of size 20 into shape (1,19)

In [99]:
a.reshape(4,-1)   #4 rows

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [101]:
a.reshape(-1,4)  #4 column

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [102]:
a.reshape(-1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [103]:
a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
### create arrays using numpy with all dimensions