### Iteration  of array:

In [1]:
l=[10,20,30,40]

In [3]:
for i in l:   #Element
    print(i)

10
20
30
40


In [4]:
for i in range(len(l)):   #index
    print(l[i])

10
20
30
40


In [8]:
#1-d array looping:

import numpy as np
a=np.array([100,20,90,89,78,76])
a

array([100,  20,  90,  89,  78,  76])

In [9]:
for i in a:
    print(i,end=" ")

100 20 90 89 78 76 

In [10]:
#2-d array

b=a.reshape(2,3)
b

array([[100,  20,  90],
       [ 89,  78,  76]])

In [11]:
for i in b:   #2d array
    for j in i:
        print(j,end=" ")

100 20 90 89 78 76 

In [12]:
### 3-d array

c=a.reshape(2,3,1)
c

array([[[100],
        [ 20],
        [ 90]],

       [[ 89],
        [ 78],
        [ 76]]])

In [13]:
for i in c:                 #3d array iteration
    for j in i:
        for k in j:
            print(k,end=" ")

100 20 90 89 78 76 

In [14]:
#keyword for iterating the array
###np.nditer

for i in np.nditer(c):
    print(i,end=" ")

100 20 90 89 78 76 

In [15]:
for i in np.nditer(b):
    print(i,end=" ")

100 20 90 89 78 76 

In [16]:
for i in np.nditer(a):
    print(i,end=" ")

100 20 90 89 78 76 

In [17]:
help(np.nditer)

Help on class nditer in module numpy:

class nditer(builtins.object)
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |  
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |  
 |  flags : sequence of str, optional
 |        Flags to control the behavior of the iterator.
 |  
 |        * ``buffered`` enables buffering when required.
 |        * ``c_index`` causes a C-order index to be tracked.
 |        * ``f_index`` causes a Fortran-order index to be tracked.
 |        * ``multi_index`` causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * ``common_dtype`` causes all the operands to be converted to
 |          a common data type, with copying or buffering as necessary.
 |        * ``copy_if_overlap`` causes the iterator to determ

### joining of array

In [18]:
a=np.arange(1,5)
b=np.arange(11,20)
print(a,end=" ")
print(b,end=" ")

[1 2 3 4] [11 12 13 14 15 16 17 18 19] 

In [19]:
c=np.concatenate((a,b))
c

array([ 1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
#2-d array

c=a.reshape(2,2)
d=b.reshape(3,3)
e=np.concatenate((c,d))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [21]:
a=np.arange(1,5)
b=np.arange(6,10)
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 6, 7, 8, 9])

In [24]:
c=a.reshape(2,2)
d=b.reshape(2,2)
print(c)
print(d)
e=np.concatenate((c,d))
e

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [25]:
### 3-d array

f=a.reshape(2,1,2)
g=b.reshape(2,1,2)
h=np.concatenate((f,g))
h

array([[[1, 2]],

       [[3, 4]],

       [[6, 7]],

       [[8, 9]]])

* To concatenate any two arrays the shape and dimensions should be same

### statistical and Math operations on arrays:

In [27]:
c

array([[1, 2],
       [3, 4]])

In [28]:
np.min(c)    #minimum value of array

1

In [29]:
np.max(c)   #maximum value of an array

4

In [30]:
a=np.array([[1,2,3],[0,9,4]])
a

array([[1, 2, 3],
       [0, 9, 4]])

In [31]:
np.min(a)

0

In [32]:
np.max(a)

9

In [33]:
## argmin() --> gives the index of minimum value of an array

a.argmin()

3

In [34]:
a.argmax()

4

In [35]:
c

array([[1, 2],
       [3, 4]])

In [36]:
c.argmin()

0

In [37]:
c.argmax()

3

In [38]:
help(c.argmin)

Help on built-in function argmin:

argmin(...) method of numpy.ndarray instance
    a.argmin(axis=None, out=None)
    
    Return indices of the minimum values along the given axis of `a`.
    
    Refer to `numpy.argmin` for detailed documentation.
    
    See Also
    --------
    numpy.argmin : equivalent function



In [39]:
## mean of array element
c

array([[1, 2],
       [3, 4]])

In [40]:
c.mean()

2.5

In [41]:
np.mean(c)

2.5

In [42]:
np.median(c)

2.5

In [43]:
c.median()  #error

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [44]:
np.var(c)  #variance of the array elements

1.25

In [45]:
np.average(c)

2.5

In [46]:
np.std(c)   #standard deviation

1.118033988749895

In [47]:
np.mode(c)    #error

AttributeError: module 'numpy' has no attribute 'mode'

In [48]:
#sum of all the elements of the array
np.sum(c)

10

In [49]:
c

array([[1, 2],
       [3, 4]])

* 1 --- row wise
* 0 --- column wise

In [50]:
np.sum(c,1)  #sum of th row elements

array([3, 7])

In [51]:
np.sum(c,0)  #sum of the column elements

array([4, 6])

### stacking:
        * arranging / organising in an appropriate way
* horizontal stacking
* vertical stacking

In [53]:
c

array([[1, 2],
       [3, 4]])

In [54]:
np.hstack(c)

array([1, 2, 3, 4])

In [55]:
d

array([[6, 7],
       [8, 9]])

In [56]:
np.vstack((c,d))

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [57]:
print(*c)

[1 2] [3 4]


In [59]:
g

array([[[6, 7]],

       [[8, 9]]])

In [60]:
np.hstack(g)

array([[6, 7, 8, 9]])

In [61]:
h=np.array([[[65,78]],[[54,32]]])
h

array([[[65, 78]],

       [[54, 32]]])

In [62]:
np.vstack((g,h))

array([[[ 6,  7]],

       [[ 8,  9]],

       [[65, 78]],

       [[54, 32]]])

In [63]:
c

array([[1, 2],
       [3, 4]])

In [64]:
np.sqrt(c)  #square root of array elements

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [65]:
np.exp(c)  #exponential of array elements

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [66]:
np.sin(c)  #sine of array elements

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [67]:
np.cos(c)   #cos of array elements

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [68]:
np.tan(c)  #tan of array elements

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [69]:
np.log(c)  #logarthmic values of the array

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [70]:
np.log2(c)   #log values with base2

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

In [71]:
np.log10(c)  #log values with base 10

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [73]:
np.power(c,3)  #cube of array elements

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [74]:
c

array([[1, 2],
       [3, 4]])

In [75]:
np.remainder(c,3)   #remainder of each array elements

array([[1, 2],
       [0, 1]], dtype=int32)

In [76]:
np.degrees(c)  #degrees of array elements

array([[ 57.29577951, 114.59155903],
       [171.88733854, 229.18311805]])

In [78]:
help(np.degrees(c))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [79]:
c

array([[1, 2],
       [3, 4]])

In [86]:
np.diff(c)   #row wise difference bydefault

array([[1],
       [1]])

In [85]:
np.diff(c,axis=0)   #column wise difference bydefault

array([[2, 2]])

In [84]:
help(np.diff)

Help on function diff in module numpy:

diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
    Calculate the n-th discrete difference along the given axis.
    
    The first difference is given by ``out[i] = a[i+1] - a[i]`` along
    the given axis, higher differences are calculated by using `diff`
    recursively.
    
    Parameters
    ----------
    a : array_like
        Input array
    n : int, optional
        The number of times values are differenced. If zero, the input
        is returned as-is.
    axis : int, optional
        The axis along which the difference is taken, default is the
        last axis.
    prepend, append : array_like, optional
        Values to prepend or append to `a` along axis prior to
        performing the difference.  Scalar values are expanded to
        arrays with length 1 in the direction of axis and the shape
        of the input array in along all other axes.  Otherwise the
        dimension and shape must match `a` except along ax

In [87]:
np.ediff1d(c)  #converts array into 1-d array and
#[1 2 3 4]
#calculates the consecutive difference of the each element

array([1, 1, 1])

In [88]:
np.mod(c,4)  #Modulous of each element in the array

array([[1, 2],
       [3, 0]], dtype=int32)

In [89]:
np.multiply(c,100)  #product of array elements with a given number

array([[100, 200],
       [300, 400]])

In [90]:
np.divide(c,2)   

array([[0.5, 1. ],
       [1.5, 2. ]])

In [91]:
a=np.array([1+2j,9+4j,8+5j])
a


array([1.+2.j, 9.+4.j, 8.+5.j])

In [92]:
np.real(a)  #real values of given array elements

array([1., 9., 8.])

In [93]:
np.imag(a) #imaginary values of given array

array([2., 4., 5.])

### Ravel and Flatten:
* Ravel : Ravel is a function used to create copy of the original array. whn any changes made in the duplicate array those will also applied in original array 
* Flatten:Flatten is a function used to create copy of the original array. whn any changes made in the duplicate array will not be applied in original array 

In [97]:
original=np.arange(1,10)
original

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
copy=original.ravel()
copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
copy[0]=100

In [102]:
copy

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [103]:
original

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [104]:
copy1=original.flatten()

In [105]:
copy1

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [106]:
original

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [107]:
copy1[2]=3000

In [108]:
copy1

array([ 100,    2, 3000,    4,    5,    6,    7,    8,    9])

In [109]:
original

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [110]:
dir(np.math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [112]:
np.reciprocal(c)

array([[1, 0],
       [0, 0]], dtype=int32)

In [115]:
help(np.ceil)

Help on ufunc object:

ceil = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array 

In [116]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [120]:
help(np.math.factorial)

Help on built-in function factorial in module math:

factorial(x, /)
    Find x!.
    
    Raise a ValueError if x is negative or non-integral.



In [121]:
np.math.factorial(5)

120

In [127]:
a=np.array([10,4,14])
a

array([10,  4, 14])

In [128]:
np.math.factorial(a[1])

24

In [ ]:
np.math.factorial(a)  #error