### Random methods

In [1]:
import numpy as np

In [3]:
np.random.randint(100)   #interger value within a given range

16

In [4]:
np.random.rand()   #float values within 0 and 1 range

0.913256160554026

In [5]:
np.random.randint(100,size=(20))  #1-d array with defined number of elements and given range

array([65, 45, 31, 76,  4, 92, 17, 16, 23, 53, 90, 39, 15, 48, 47, 76, 51,
       82, 60, 12])

In [6]:
np.random.randint(50,size=(2,3))  #2-d array

array([[46, 47,  7],
       [13, 17,  6]])

In [7]:
np.random.randint(10,size=(2,2,3))  #3-d array

array([[[4, 8, 9],
        [8, 7, 3]],

       [[1, 5, 1],
        [0, 6, 8]]])

In [8]:
np.random.choice([10,7,8,9,5])

7

In [9]:
np.random.choice([10,9,8,7,6,5],size=(3,2))

array([[ 5, 10],
       [ 9,  8],
       [ 9,  7]])

In [10]:
np.random.choice([10,9,8,7,6,5],size=(3,2,1))

array([[[10],
        [ 9]],

       [[ 6],
        [ 9]],

       [[10],
        [ 9]]])

In [11]:
np.random.randn(10)  #positive and negative values in defined number

array([-1.47903525,  0.07221055, -1.07466384,  1.92109491,  0.56478608,
       -0.48510333,  1.62085224, -0.29188818,  0.73552663, -0.54990643])

In [12]:
np.random.normal()   #normal distribution

0.35601690906108857

### Array Filtering

In [14]:
a=np.array([90,89,18,67,20])
b=[False,True,True,True,False]
c=a[b]
c

array([89, 18, 67])

In [16]:
#print the values which are greater than 20
#a=np.array([90,89,18,67,20])
b=[]  #b=[True,True,False,True,False]
for i in a:
    if i>20:
        b.append(True)
    else:
        b.append(False)
        
c=a[b]
c  

array([90, 89, 67])

In [17]:
d=a>20
e=a[d]
e

array([90, 89, 67])

In [18]:
a.T

array([90, 89, 18, 67, 20])

In [19]:
a.reshape(5,1)

array([[90],
       [89],
       [18],
       [67],
       [20]])

In [20]:
a.T   

array([90, 89, 18, 67, 20])

In [21]:
e

array([90, 89, 67])

### Pandas

* Pandas is a built in library using for data analysis. 
* Used for data manipulations,visualisations,building machine learning models
* There are two main data structures in pandas . Series and DataFrames

In [22]:
import pandas as pd

In [23]:
pd.__version__

'1.0.1'

### pandas series

* A series is similar to a 1-D ARRAY,  and contains the values of same type.
* dataframe is simply a table where each column is a pandas series
* creating series
    * List
    * Tuple
    * Dictionary
    * Numpy
    * Date_Range
* Series indexing

In [24]:
#creating pandas series using list

l=[89,7,6,70,5,68]
p=pd.Series(l)
p

0    89
1     7
2     6
3    70
4     5
5    68
dtype: int64

In [25]:
#creating pandas series using tuple

t=(89,67,65,45)
s=pd.Series(t)
s

0    89
1    67
2    65
3    45
dtype: int64

In [26]:
p1=pd.Series(t,index=['a','b','c','d'])
p1

a    89
b    67
c    65
d    45
dtype: int64

In [85]:
# creating series with dictionary

d={'amar':69,'sita':90,'ram':78,'gopi':45,'vasu':34}
s=pd.Series(d)
s

amar    69
sita    90
ram     78
gopi    45
vasu    34
dtype: int64

In [86]:
s.index=[10,'a','b','c','d']  #Reindexing

In [87]:
s

10    69
a     90
b     78
c     45
d     34
dtype: int64

In [88]:
s['d']  #getting values using index

34

In [89]:
s[10]

69

In [90]:
s[1:3]  #start,stop

a    90
b    78
dtype: int64

In [91]:
s

10    69
a     90
b     78
c     45
d     34
dtype: int64

In [92]:
s[1:4:2]  #start,stop,step

a    90
c    45
dtype: int64

In [93]:
s

10    69
a     90
b     78
c     45
d     34
dtype: int64

In [94]:
s.index=[20,21,22,23,24]

In [95]:
s

20    69
21    90
22    78
23    45
24    34
dtype: int64

In [96]:
s.index=np.arange(30,35)
s

30    69
31    90
32    78
33    45
34    34
dtype: int64

In [97]:
s=pd.Series("APSSDC",index=[1,2,3,4])
s

1    APSSDC
2    APSSDC
3    APSSDC
4    APSSDC
dtype: object

In [ ]:
#Creating a series object having power of index value

0 -- 0
1 -- 1
2 -- 4
3 -- 9
4 -- 16
.
.
.
.
10 -- 100

In [41]:
s=pd.Series([i**2 for i in range(11)])
s

0       0
1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
dtype: int64

In [43]:
n=int(input())
s=pd.Series([i**2 for i in range(1,n+1)],
            index=list(range(1,n+1)))
s

8


1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
dtype: int64

In [45]:
n=int(input())
d={i:i**2 for i in range(1,n+1)}  #dictionary comprehension
p=pd.Series(d)
p

6


1     1
2     4
3     9
4    16
5    25
6    36
dtype: int64

In [59]:
s=pd.Series(np.square(np.arange(1,10)))
s.index=range(1,10)
s

1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [60]:
## Date Range method

dates=pd.date_range(start="2020-10-5",end="2020-10-12")
dates

DatetimeIndex(['2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08',
               '2020-10-09', '2020-10-10', '2020-10-11', '2020-10-12'],
              dtype='datetime64[ns]', freq='D')

In [61]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs) -> pandas.core.indexes.datetimes.DatetimeIndex
    Return a fixed frequency DatetimeIndex.
    
    Parameters
    ----------
    start : str or datetime-like, optional
        Left bound for generating dates.
    end : str or datetime-like, optional
        Right bound for generating dates.
    periods : int, optional
        Number of periods to generate.
    freq : str or DateOffset, default 'D'
        Frequency strings can have multiples, e.g. '5H'. See
        :ref:`here <timeseries.offset_aliases>` for a list of
        frequency aliases.
    tz : str or tzinfo, optional
        Time zone name for returning localized DatetimeIndex, for example
        'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
        timezone-naive.
    normalize : bool, default False
        Normalize start/

In [62]:
#creating series by using numpy array

n=np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
s=pd.Series(n,index=np.arange(20,30))
s

20    0
21    1
22    2
23    3
24    4
25    5
26    6
27    7
28    8
29    9
dtype: int32

In [64]:
n1=np.array([23,67,8,9,90])
n1

array([23, 67,  8,  9, 90])

In [66]:
s1=pd.Series(n1)
s1

0    23
1    67
2     8
3     9
4    90
dtype: int32

In [73]:
s2=pd.Series(np.array([90,89,87,67]),index=['a','b','c','d'])
s2

a    90
b    89
c    87
d    67
dtype: int32

In [76]:
s

20    0
21    1
22    2
23    3
24    4
25    5
26    6
27    7
28    8
29    9
dtype: int32

In [77]:
s[0:2]

20    0
21    1
dtype: int32

In [78]:
#fancy indexing

s[[26,27,28]]

26    6
27    7
28    8
dtype: int32

In [79]:
#Nan --> not a number

d={"a":45,"b":56,"c":78,"d":np.nan,"y":"abc"}
s=pd.Series(d)
s

a     45
b     56
c     78
d    NaN
y    abc
dtype: object

In [80]:
s["d"]

nan

In [81]:
s["d"]=787  #assigning value to a nan value

In [82]:
s

a     45
b     56
c     78
d    787
y    abc
dtype: object